export const NamingConstants = {
  BLOCK_CONTENT: 'blockContent',
  HERO_DATA: 'heroData',
  IMAGE_DATA: 'imageData',
  TEXT_DATA: 'textData',
  LINK_DATA: 'linkData',
  BUTTON_DATA: 'buttonData',
  VIDEO_DATA: 'videoData',
  AUDIO_DATA: 'audioData',
  ARTICLE: 'article',
  TITLE: 'title',
  SUBTITLE: 'subtitle',
  PUBLISH_DATE: 'publishDate',
  DESCRIPTION: 'description',
  IMAGE: 'image',
  PRIMARY_TEXT: 'primaryText',
  SECONDARY_TEXT: 'secondaryText',
  EVENT: 'event',
  PRIMARY_CATEGORY: 'primaryCategory',
  CTA: 'cta',
  LAST_MODIFICATION: 'lastModification',
  INTERNAL_LINK_URL: 'internalLinkUrl',
  LINK_URL: 'linkUrl',
  SLUG: 'slug',
  TAGS: 'tags',
  BIOGRAPHY: 'biography',
  MARKETO_FORM_ID: 'marketoFormId',
  EMAIL_ADDRESS: 'emailAddress',
  JOB_TITLE: 'jobTitle',
  START_DATE: 'startDate',
  END_DATE: 'endDate',
  SOCIAL_MEDIA_IMAGE: 'socialMediaImage',
};

export const CompoundNames = {
  ARTICLE_TITLE: 'article.title',
  ARTICLE_DATE: 'article.publishDate',
  CTA_LINK_URL: 'cta.linkUrl',
  EVENT_START_DATE: 'event.startDate',
};