export const Dropdowns = {
  BlogSources: [
    {title: 'Default', value: 'default'},
    // Add more blog sources as needed
  ],
  TeaserContexts: [] as Array<{title: string; value: string}>,
  CtaIcons: [] as Array<{title: string; value: string}>,
  CtaActions: [] as Array<{title: string; value: string}>,
  ArticleActionIcons: [] as Array<{title: string; value: string}>,
  LabsArticleTypes: [] as Array<{title: string; value: string}>,
  LabsContentTypes: [] as Array<{title: string; value: string}>,
  IndividualRoles: [] as Array<{title: string; value: string}>,
  AvailableThemes: [] as Array<{title: string; value: string}>,
  AvailableIcons: [] as Array<{title: string; value: string}>,
  LinkTypes: [
    {title: 'Internal', value: 'internal'},
    {title: 'External', value: 'external'},
  ] as Array<{title: string; value: string}>,
  MetaRobots: [] as Array<{title: string; value: string}>,
  F5IconColors: [] as Array<{title: string; value: string}>,
  F5EventTypes: [] as Array<{title: string; value: string}>,
  f5ComPageLocations: [] as Array<{title: string; value: string}>,
  GoPageAvailableLanguages: [] as Array<{title: string; value: string}>,
  GoPageTypes: [] as Array<{title: string; value: string}>,
  AppworldPageLocations: [] as Array<{title: string; value: string}>,
  f5CaseStudyIndustries: [] as Array<{title: string; value: string}>,
  f5CaseStudyPillars: [] as Array<{title: string; value: string}>,
  f5CaseStudyRegions: [] as Array<{title: string; value: string}>,
  F5DemoCenterDemoTypes: [] as Array<{title: string; value: string}>,
  F5DemoCenterProductGroups: [] as Array<{title: string; value: string}>,
  ProductCategoryDataLayer: [] as Array<{title: string; value: string}>,
  F5DemoCenterPlatformDomains: [] as Array<{title: string; value: string}>,
  F5DemoCenterSolutionAreas: [] as Array<{title: string; value: string}>,
  F5DemoCenterArchitectureRelevance: [] as Array<{title: string; value: string}>,
  F5DemoCenterEduLevel: [] as Array<{title: string; value: string}>,
  LabsLargeCardsSelectionMethods: [] as Array<{title: string; value: string}>,
  BreadcrumbOptions: [] as Array<{title: string; value: string}>,
  F5CardVariations: [] as Array<{title: string; value: string}>,
  ContentAlignmentOptions: [] as Array<{title: string; value: string}>,
  ColumnCounts: [] as Array<{title: string; value: string}>,
  TwoColumnSpacing: [] as Array<{title: string; value: string}>,
  f5BackgroundColors: [] as Array<{title: string; value: string}>,
  f5DarkBackgroundColors: [] as Array<{title: string; value: string}>,
  FooterCredibilityTypes: [] as Array<{title: string; value: string}>,
  LeadershipIndicators: [] as Array<{title: string; value: string}>,
  SideBySideTypes: [] as Array<{title: string; value: string}>,
  SideBySideDisplays: [] as Array<{title: string; value: string}>,
  DynamicCardOptions: [] as Array<{title: string; value: string}>,
  ContentTypeDataLayer: [] as Array<{title: string; value: string}>,
  DateDataLayer: [] as Array<{title: string; value: string}>,
  DeploymentModeDataLayer: [] as Array<{title: string; value: string}>,
  GTMPriorityDataLayer: [] as Array<{title: string; value: string}>,
  IndustryDataLayer: [] as Array<{title: string; value: string}>,
  RegionDataLayer: [] as Array<{title: string; value: string}>,
  SolutionAreaDataLayer: [] as Array<{title: string; value: string}>,
  SolutionUseCaseDataLayer: [] as Array<{title: string; value: string}>,
}

